### ISSUE TITLE
Can not do anything.

### ISSUE THREAD

**Issue by Jman-Jd10** [r3eckon/BNG-BeamLegalRacing#10]
I have the Ui But just for player stats and BeamLR but there are no markers on the map

**Comment by r3eckon** [comment]
Clean install in the userfolder, carefully follow the instructions, this mod can't be installed like a regular mod.

**Comment by abodyeasy** [comment]
> I have the Ui But just for player stats and BeamLR but there are no markers on the map

Try to remove all mods, then clean the userfolder, if it doesn't work just uninstall BeamNG and install it again!
