### ISSUE TITLE
Can't modify rear tires

### ISSUE THREAD

**Issue by Krakon01** [r3eckon/BNG-BeamLegalRacing#14]
When I put on the 17x7 hirochi sunsport wheels on front and 17x9 hirochi sunsport wheels on the rear, I have two options to change the rear wheels on the car in the menu, but both of them show the front wheels that I can change. A workaround is to temporarily remove the front wheel to modify the rear tires.

**Comment by r3eckon** [comment]
I just tried and didn't encounter the issue using your steps, I can see all front/rear tire/wheel slots as expected. When you get issues like that one with the UI try CTRL+F5, it will force a refresh of UI data and can often solve such issues.
