### ISSUE TITLE
ETK body type not preserved from used car lot

### ISSUE THREAD

**Issue by DookieAllan** [r3eckon/BNG-BeamLegalRacing#16]
After purchasing a sedan-type ETK from the used car lot, I changed to it at my garage only to be met with the wagon-type ETK. I've actually had this happen before as well when purchasing a van that was painted funny and missing components but when I got it back to my garage ts was bone stock.
 
 BTW, is there a known issues area here or on the forum, aside from the user-submitted ones? I don't wanna bug anyone with issues that are already being tracked.

**Comment by r3eckon** [comment]
This sounds like installation issues. How did you install the mod? If you installed as a zip mod this kind of problem can happen. Make sure you carefully follow the install instructions on the github readme. You have to extract the contents of the zip file directly inside the root of your BeamNG userfolder for the mod to work properly.
