### ISSUE TITLE
Can't seem to locate backup in Userfolder/beamlr

### ISSUE THREAD

**Issue by DookieAllan** [r3eckon/BNG-BeamLegalRacing#17]
I checked all 3 user folders, my user, default, and public. However, there seems to be no BeamLR folder in any. I also checked the Steamapps Beamng folder to no avail.

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/151474582/19b79ab1-8792-4879-8801-a0f59317ccb1)

**Comment by r3eckon** [comment]
It's the [BeamNG Userfolder](https://documentation.beamng.com/support/userfolder/), which is also where you're supposed to install the mod. This is explained in the install instructions.
