### ISSUE TITLE
No Italy start point

### ISSUE THREAD

**Issue by Razer11** [r3eckon/BNG-BeamLegalRacing#18]
I cannot for the life of me find the mission start point to get into the BLR mission in the Italy map, it doesn't show up in the reported location or on the mission list.

The spawns / mission starts are in and working on both the other maps and the rest of the Mod seems to be working perfectly

![Italy2](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/60428709/9f404e94-b8c3-44cb-af35-87b38f996ea0)
![Italy](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/60428709/addb930f-5620-4fe7-9802-0e74c33e3fd4)

**Comment by r3eckon** [comment]
Most likely you installed the wrong version or the mod isn't correctly installed. userfolder/gameplay/missions should contain a folder called "BeamLegalRacingItaly" which contains the mission files for the map.
