### ISSUE TITLE
Parts Store

### ISSUE THREAD

**Issue by A1C6** [r3eckon/BNG-BeamLegalRacing#2]
I cannot find the parts store for the life of me!
I go into the menu and it says: 
_**Buy Parts**_
_**Get to a shop!**_
![screenshot_2022-11-04_19-54-46](https://user-images.githubusercontent.com/110947491/199944788-9f0a4893-72ac-43c3-bc00-717ada03bde2.png)
(I have tried places)

Also what happened here?!
![screenshot_2022-11-04_19-54-39](https://user-images.githubusercontent.com/110947491/199944849-fef387f7-ac37-4291-a73f-820675e9e601.png)

**Comment by r3eckon** [comment]
It's near the start zone right next to the player garage, the spot doubles as the mission giver where you get the delivery missions. So when you see the window for Mission Giver pop up you can access that menu. On Utah there aren't enough buildings for dedicated part shop. 

And yeah I've seen that happen before lmao, I'm gonna need to turn down traffic risk but trucks really don't know how to handle that corner. There's another spot next to the highway in the dirt roads where pretty much 100% of all traffic crashes at the same turn.

**Comment by A1C6** [comment]
Thanks!

**Comment by A1C6** [comment]
Why didn’t it close?
Let’s hope it does now…
