### ISSUE TITLE
Broken UI - BeamNG 0.31 + BeamLR 1.14.1

### ISSUE THREAD

**Issue by ZdrytchX** [r3eckon/BNG-BeamLegalRacing#22]
The following doesn't work for me as far as I've tried:
* BeamLR main menu (doesn't even appear)
* fuel stations (Starts refueling sound but nothing happens)
* player health (doesnt exist on the player status window)
* Repair shops unusable
* There was one instance where the final road gate failed to trigger (on west coast USA) driving over it and consequently a race was unwinnable

edit: please wait while I try out a fresh user directory
edit2: it seems I've now lost all my saves in my own stupidity. Starting afresh it seems to be working but if there's something broken I'll create a new issue

**Comment by ZdrytchX** [comment]
* close *

**Comment by r3eckon** [comment]
Glad you got it sorted out, remember to back up your beamLR folder before updating or playing around with files to ensure you don't lose save data.

**Comment by r3eckon** [comment]
> Is there supposed to be player health in the player status window?? i remember those were on the older versions of BeamLR.

It was removed due to G force bugs in BeamNG causing random health drop, I tried many workarounds but nothing worked so it was removed but you can still die from a single high G force impact (>80Gs).
