### ISSUE TITLE
Having no fuel results in a vehicle that cannot be refueled

### ISSUE THREAD

**Issue by ZdrytchX** [r3eckon/BNG-BeamLegalRacing#23]
There doesn't seem to be a way to obtain fuel if the vehicle has no fuel. Perhaps add an option for the user to purchase fuel while at home or a garage at an upmarked price depending on how far is the closest fuel station.

I ended up without fuel while at a garage after swapping out a fuel tank and effectively soft locked myself.

**Comment by r3eckon** [comment]
Good idea, this should be easy enough to add to the garage and player garage menus.
