### ISSUE TITLE
Police arrest me when they're nowhere near

### ISSUE THREAD

**Issue by Razer11** [r3eckon/BNG-BeamLegalRacing#28]
I get "Busted" and fined even though there are no police cars anywhere near me

**Comment by r3eckon** [comment]
The police is fully vanilla, the mod only shows police information in a UI window. So this most likely is a bug with BeamNG. Try recreating the bug in freeroam and report it to BeamNG devs in the discussion thread for the latest update. Police AI is known to be quite buggy, if you look around the forum you'll see a bunch of posts about these issues.
