### ISSUE TITLE
Nordschleife races AI not working

### ISSUE THREAD

**Issue by Real-Racing-Rookie** [r3eckon/BNG-BeamLegalRacing#29]
thanks for fixing the previous issue however, now that thats sorted when i loaded into this race the AI would not move and the checkpoints didnt show up.

![316292351-cac2aad0-3a1c-45b6-9c44-755b201576fb](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/124314510/79f965d9-6296-491c-b576-e5a3f998949d)

**Comment by r3eckon** [comment]
[I already answered this on your other question.](https://github.com/r3eckon/BNG-BeamLegalRacing/issues/26#issuecomment-2016724458)

**Comment by Real-Racing-Rookie** [comment]
yes and it started to work but now the AI will not move and the checkpoints dont exist the other issue is fixed, thanks.

**Comment by r3eckon** [comment]
Check the world editor for these simgroups:

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/7356f72e-6020-4761-b1d7-b7239b1bd2a4)

If they're missing it means you have level files overwriting my addon. You need to delete any folder labeled ks_nord from **userfolder/levels** and **game folder/levels.** Remember that this addon is supposed to be installed as a regular zip mod, don't extract the files.

If the simgroups are missing clear console before starting the race and then send me a screenshot of errors if there are any.

**Comment by Real-Racing-Rookie** [comment]
before starting race but after opening beamlr mission:
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/124314510/06cfdcc2-f8d3-46bc-9791-a932d0c1b2a2)
after starting race:
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/124314510/bac509e3-9cf5-4901-8560-8d8ab42a0f47)1
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/124314510/2726c6fd-0b36-4326-a3db-2aa85ade27d4)2
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/124314510/b0cfb147-32fa-4f80-b3fc-cfaf7eb3caf4)3
and theres about 100 more screenshots i could take, let me know if you need the rest but hopefully its repeating or all similar

**Comment by r3eckon** [comment]
I'm assuming the simgroups are missing from world editor tree. That means something in the userfolder or game folder is overwriting the addon files, or you incorrectly installed the addon by extracting the files and ended up deleting the level edits. 

If you think everything is installed correctly I'd like to confirm the folder structure. 
1. Navigate to the userfolder
2. Hold down the SHIFT key > Right click in the folder empty space > "Open PowerShell window here"
3. Type this line and hit enter
`tree > tree.txt /a /f`

This will create a text file called **tree.txt** in your userfolder which contains the folder structure. Upload it here so I can have a look and if it's as it should be.

However at this point the simpler option is to reinstall the addon in a clean userfolder:
1. Move the content of your userfolder somewhere to back them up 
5. Delete the userfolder contents. 
6. Install BeamLR
7. Install the addon 
8. Copy the beamLR folder from your back up to the new userfolder to restore your career

**Comment by Real-Racing-Rookie** [comment]
[tree.txt](https://github.com/r3eckon/BNG-BeamLegalRacing/files/14765396/tree.txt)

**Comment by r3eckon** [comment]
From the folder structure I can see that the addon isn't installed properly. The zip file should be in the **userfolder/mods** folder. The game loads the addon zip file before the map mod which causes changes in the addon to be overwritten. This is why it must be in the **mods** folder and starts with "zz" to force it to load after the level mod.

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/5ff653eb-2cd7-4222-98ae-45aa8d63fc90)

Also seems you cloned the repository. That shouldn't be an issue however you don't need to do that. Just download the latest release zip for the main mod (link is in instructions), that should be extracted in the userfolder. Then download whatever addons zip files you want, these are to be added in the **mods** folder as is, without extracting.
