### ISSUE TITLE
Beam 0.32 Broken.. ofc

### ISSUE THREAD

**Issue by Naniwara** [r3eckon/BNG-BeamLegalRacing#30]
hihi, first time ever using github and i'm somewhat of an outsider (if there's a twitter, discord, or whatever, i haven't seen it due to me missing it and not looking well enough)

0.32 seems to not be functional at all, throwing small errors that can't really be understood by me, but are in general causing the game to not load the garage or any other UI other than the base one, causing the game to be basically softlocked from the start.. i assume this is just already an issue since the update but i wanted to make sure,

**Comment by r3eckon** [comment]
Latest release (1.15) should fix issues related to 0.32 so if you still have issues with the new version back up your userfolder, delete it and start the game to have a clean userfolder. Then carefully follow the install instructions.

**Comment by Naniwara** [comment]
i been playing it only on utah (due to me being a little braindead) BUT it still hasn't been working from a fresh reinstall (reinstalled beamng instead of changing from 0.31 to 0.32) so no file errors should have occurred.

**Comment by r3eckon** [comment]
[Follow the instructions on this post](https://github.com/r3eckon/BNG-BeamLegalRacing/issues/29#issuecomment-2019826628) and upload the resulting tree.txt file here so I can check if you installed the mod properly.

**Comment by Naniwara** [comment]
okay so i.. don't know what tree.txt file to find exactly as it is just NOT there, i unzipped the zip file in the beamng folder that you get to via clicking for it on steam (as the "moved here" thing was gone somehow), as a sidenote there was an error that said something about "missing barstow" which MIGHT be caused by a mod (haven't brute forced all mods off yet but there's a barstow mod in there for sure) and the game even if not loading said barstow gives me a miramar, and sometimes spawns me just underground entirely.

**Comment by r3eckon** [comment]
If you installed in the game folder that can cause all sorts of problems. Please carefully read the install instructions. There is a link within them to help you find the BeamNG **userfolder** which is where the mod should be installed. That's not the same location as the game install folder. You can access the **userfolder** via the BeamNG launcher. As for the tree.txt file the post I linked tells you how to create it. It'll be hard for me to help you figure things out if you don't carefully read the instructions.

**Comment by Naniwara** [comment]
alright i just mis assumed, last time i did this i was sent to the userfolder,not steam's, you think verifying the game files is enough for the game to fix itself? or am i just gonna have to reinstall

**Comment by r3eckon** [comment]
I think integrity verification only looks for missing or broken files to redownload so if you don't want to redownload everything, look at the folders in the BeamLR archive and delete folders with the same name in your BeamNG install folder. Some folders have been merged so after that verify the game files on steam and it should be restored to its original condition. 

So basically you have these folders to remove from your game install folder:
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/92376e5a-0f80-45e5-8da4-b503eef0f366)

This is what my install folder looks like for reference. I marked all the merged folders that will need to be re-downloaded after they're deleted. It's like 800 MB in total so should be faster than a full reinstall. 
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/012cc708-314e-42ad-88d8-eb24f441701b)

If you have the internet speed a full reinstall would be safer but as long as you get rid of all the folders from my mod before verifying integrity it should fix the issues. Then install the mod in the userfolder and carefully follow the instructions. Let me know if that fixes your issue.

**Comment by Naniwara** [comment]
thanks and sorry for wasting your time, i'll close this, this was entirely an user error on my end, i went for the steam folder assuming it was the userfolder (please specify that so someone with a brain as unwrinkled as mine does not mess up!) but apologies for the troubles. i'm really sorry and hope you have a great day/night... also as an idea, why not a "pick your own shitbox" start instead of appearing in something like a burnside that burns itself? (happened to me trying to do a delivery and it was funny as hell)

**Comment by r3eckon** [comment]
No worries, glad I could help you figure this out! This is actually a common issue for new players of the mod, I'll try to add further clarifications in the instructions. Just let me know if you encounter other issues. I'll keep the idea in mind for a start difficulty where you pick your own car, could be just enough money to go to the used car dealership and pick a car which is basically how SLRR does it.

**Comment by Naniwara** [comment]
in easy difficulty and whenever i went, MOST cars were buyable, then there's that one dinked up legran, but i'll close the thingy now, have a great time, but another request would be more difficult but, what about making johnson valley a playable area? it'd be fun to use the long road as an actual full on delivery area and having to get a more offroadey car and a car for just proper top speed drag racing i guess, seems like a cool thing (if it's a thing i will explode my starter car into a wall), also.. make the starter car sell for over 100 bucks..
