### ISSUE TITLE
error code 0x00000001 upon loading purchased cars.

### ISSUE THREAD

**Issue by Naniwara** [r3eckon/BNG-BeamLegalRacing#32]
whenever i try loading a  car after buying it it throws me this error, i don't know if it's due to me using modded parts or something as such but im confused. sorry for lacking so much info

**Comment by r3eckon** [comment]
Reinstall in a clean userfolder and carefully follow install instructions, don't use any mods at first, if it still bugs send me the log files (in userfolder, files that finish in .log)

**Comment by Naniwara** [comment]
okay disabling mods worked (at least for now)  sorry for being annoying..

**Comment by Naniwara** [comment]
i TAKE BACK WHAT I JUST FUCKING SAID, i'll do what you said if i figure it out (im really not understanding it) it only happens on car loading.

**Comment by r3eckon** [comment]
In the [BeamNG userfolder](https://documentation.beamng.com/support/userfolder/) there are .log files, I need them to check for errors. These are the ones I need, don't worry if some of them are missing but there should at least be **beamng.log** in there:

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/c23658f3-bf0a-43c5-947e-df32800a7c83)

Keep in mind disabling mods might not fix such issues especially if you have other userfolder mods installed like BeamMP. If you haven't already you should: 

1. Back up the contents of the userfolder somewhere
2. Delete the userfolder
3. Start BeamNG so the game creates a fresh userfolder
4. Close BeamNG
5. Install BeamLR in that userfolder carefully following the instructions. 
 
This will ensure nothing can interfere with the mod.

**Comment by r3eckon** [comment]
I'll close this for now since there hasn't been an update in 2 weeks, I'm assuming you fixed it. Make sure to include log files if you get the issue again.
