### ISSUE TITLE
Repair deleted everything except frame and engine

### ISSUE THREAD

**Issue by WallK** [r3eckon/BNG-BeamLegalRacing#34]
I've went to garage and clicked "Repair selected" which had a cost of mandatory repairs
My car respawned in this state
![BeamNG drive x64_2024-07-17_10-17-29](https://github.com/user-attachments/assets/27313556-7451-4171-89bb-4a026ff87a8d)

What I did: I've sold most of the stuff on the car, like a bed, both doors and bumpers
Didn't touch engine parts or wheels
Then I tried racing, hit a stone, took a tow truck back and repaired

**Comment by r3eckon** [comment]
This is not a bug. If you only repair selected parts anything not selected will be deleted. Anything that isn't damaged but is attached to a damaged part as per the part edit tree will be added to your inventory. For example if you damage the "Body" part and don't select it for repair, it'll remove every part that's linked to it like doors, fenders, hood, dashboard, etc. If these parts aren't damaged you'll find them in the part inventory.

**Comment by WallK** [comment]
Oh wow, did I miss this described somewhere in UI?
Thanks for clarification!

**Comment by r3eckon** [comment]
No it's not really explained anywhere other than the github readme, I'll add a warning about this for new players.
