### ISSUE TITLE
fatal lua error

### ISSUE THREAD

**Issue by spencerdre** [r3eckon/BNG-BeamLegalRacing#35]
when i try to load the Ai race i get a fatal Lua error 
![20240725141251_1](https://github.com/user-attachments/assets/b5fc9cc1-13c8-4fae-974f-3c4a26e9aa5c)

**Comment by r3eckon** [comment]
This map isn't compatible with the mod. Career maps are Utah, East Coast, Italy and West Coast. Track Events (must be joined from career) are available on Hirochi Raceway, Automation Test Track and the Nordschleife modded map which requires the addon and map to be installed.

[Read this section of the readme for more information on how to get started.](https://github.com/r3eckon/BNG-BeamLegalRacing/tree/main?tab=readme-ov-file#getting-started)

Not sure what's going on in your screenshot, looks like you edited a UI layout to add the BeamLR menu or you removed some apps from the BeamLR layout. You shouldn't do that. In a compatible map, drive into the BeamLR blue marker from freeroam (they're close to the spawns indicated in the above link, you can also find them from the big map UI) and start the mission.
