### ISSUE TITLE
BUGS NA LOJA OU NA HORA DE INSTALAR PEÇAS

### ISSUE THREAD

**Issue by FelpszadaSc** [r3eckon/BNG-BeamLegalRacing#36]
Bom as vezes o mod está dando alguns bugs como OBS: compro um motor instalo ele no carro e ele retira algumas peças, porém se clicar para usá-la ela volta, mas as vezes acontece que a peça já está instalada no carro porém consta que não está instalada , assim bugando e não dando mais para retirar ela ou usar, mesmo vendendo e comprando outra

**Comment by FelpszadaSc** [comment]
Aliás, poderia criar ou já tem um servidor sobre o mod/modo de jogo no Discord para podermos conversar sobre jogar juntos, prints ETC

**Comment by r3eckon** [comment]
I'm currently investigating this bug but I can't recreate it. No discord, I don't want to have to mod a server. Please use english to report issues, if I can put your posts through google translate to read them you can do the same before posting them.

**Comment by r3eckon** [comment]
Should be fixed in 1.16.2
