### ISSUE TITLE
Black Sky

### ISSUE THREAD

**Issue by saxtz** [r3eckon/BNG-BeamLegalRacing#37]
whenever i load one of the maps that it changes the textures glitch and it becomes all dark black/gray

**Comment by r3eckon** [comment]
Clear your cache, if that doesn't work reinstall the mod in a clean userfolder (backup userfolder, delete it, start BeamNG so it creates a new one), carefully follow the install instructions.

**Comment by vjacal** [comment]
I already cleared the cache, reinstalled the mod and the game and the sky is still dark

**Comment by r3eckon** [comment]
Don't just reinstall the mod, delete the userfolder before installing and don't just throw the zip file in the mods folder, follow the install instructions.

**Comment by vjacal** [comment]
yes I did that, and it remains the same

**Comment by r3eckon** [comment]
I tested on a different computer, clean userfolder, latest version of the game (0.32.5), latest version of the mod, installed according to instructions. I got no issue with black textures. I don't think this is a problem with the mod. 

Try playing with texture quality setting see if it changes anything. If you're using vulkan try the normal renderer. If you're on linux, MacOS or steam deck this is a known issue, look it up. Try updating GPU drivers. If it happens in safe mode it's definitely not a problem with the mod.  If it doesn't happen in safe mode you're maybe not installing correctly. There's a video out there showing incorrect instructions, only follow my install instructions. If you're running a pirated version the outdated level files might not be compatible with my changes.

**Comment by DarkBuzzz** [comment]
> sempre que eu carrego um dos mapas, ele muda a falha de textura e fica tudo preto/cinza escuro

Estou com mesmo problema!! já instalei conforme o tutorial, reistalei o mod e não mudou nada, está tudo atualizado! você conseguiu arrumar o seu?? se não vou tentar esperar mais algumas atualizações pra ver se resolve!

**Comment by r3eckon** [comment]
This is either a rendering API issue, conflict with a different mod, incorrect install, broken textures in cache, outdated base level files or something else that's most likely not an issue with this mod. Try the troubleshooting guide, make sure your game is up to date, completely delete your userfolder and start from fresh, don't use any other mods.

It's very unlikely that this mod is to blame for this issue, level files aren't affected by race conditions and other system dependent problems. This mod doesn't change textures and the only modifications done to levels are added waypoints and tweaks to AI decalroads.
