### ISSUE TITLE
Bug when changing cars in our house 

### ISSUE THREAD

**Issue by FelpszadaSc** [r3eckon/BNG-BeamLegalRacing#38]
When I select a car and click to pick it up, it simply doesn't load, I'm left with what I already had, and I can't select any more, I just continue with what I already had.

And it also happens that the car disappears completely and gives a Lua error, thus bugging the save, and not being able to do anything else.

I hope you select it soon, because the mode is incredible.

🇧🇷 🇧🇷 🇧🇷 🇧🇷 🇧🇷 🇧🇷 🇧🇷 🎮❤

**Comment by r3eckon** [comment]
Follow the [troubleshooting guide](https://github.com/r3eckon/BNG-BeamLegalRacing/blob/main/troubleshooting.md) and see if it helps. If not post errors, logs, etc.

**Comment by FelpszadaSc** [comment]
Ok

**Comment by FelpszadaSc** [comment]
> Siga o [guia de solução de problemas](https://github.com/r3eckon/BNG-BeamLegalRacing/blob/main/troubleshooting.md) e veja se ele ajuda. Se não, poste erros, logs, etc.


I redid the installation of the mod completely from scratch, I deleted the mod, I did an integrity check on Steam, and I installed it, I put my save and it keeps giving the error, I click to change cars and it doesn't start and the car menu freezes

 Could it be my save game is corrupted?
 
 I left a video to watch
 

https://github.com/user-attachments/assets/adef1c7c-0f14-46b3-a2a7-ae4afa1f5caf

**Comment by r3eckon** [comment]
Your video is too blurry for me to see the errors in console. Post logs. But I suggest you try the same thing you did without restoring your save files first, if the issue doesn't happen anymore something is wrong with the save files.

**Comment by FelpszadaSc** [comment]
[beamng.1.log](https://github.com/user-attachments/files/16936160/beamng.1.log)
[beamng.2.log](https://github.com/user-attachments/files/16936162/beamng.2.log)

**Comment by r3eckon** [comment]
No new reply so I'm assuming the new save or new version of the mod fixed the issue. Re-open the issue if it happens again on the latest version of the mod.

**Comment by FelpszadaSc** [comment]
I've already updated the mod and I'm throwing any bug again where the car disappears, warning

Thanks for your attention, the mod is incredible
