### ISSUE TITLE
repair dosen't repairs

### ISSUE THREAD

**Issue by Zeroblacck** [r3eckon/BNG-BeamLegalRacing#39]
![image](https://github.com/user-attachments/assets/c2f69820-7d47-4b2e-944d-1d137ec6c584)

**Comment by r3eckon** [comment]
Screenshots of errors are useless, post log files.

**Comment by r3eckon** [comment]
Actually never mind, I managed to get the issue and fix it for next version. I posted a patched file on the forum if you want to fix it yourself.
