### ISSUE TITLE
Parking Markers

### ISSUE THREAD

**Issue by abodyeasy** [r3eckon/BNG-BeamLegalRacing#4]
Could you please fix the parking markers where the race begins? I can't seem to be able to get my bluebuck in there because of how tall my bluebuck is...
![image](https://user-images.githubusercontent.com/65369877/231488317-7d840934-4a4c-4f30-a8b0-7efa22298f66.png)

**Comment by abodyeasy** [comment]
@

**Comment by abodyeasy** [comment]
I kinda fixed it by removing the rear bumper, and towing hitch.
but still, the marker needs to be taller!

**Comment by r3eckon** [comment]
Yeah I noticed it was a bit tight with some configs, I'll increase the length for next update.

**Comment by abodyeasy** [comment]
Thanks!
