### ISSUE TITLE
Auto-Sales broken

### ISSUE THREAD

**Issue by Zeroblacck** [r3eckon/BNG-BeamLegalRacing#40]
![image](https://github.com/user-attachments/assets/e0d374b7-cbd3-4863-9e20-e26a31bfbdea)
the menu to go to the next car and cancel just don't shows up, my car just dissapers when i entry in buy menu..

**Comment by r3eckon** [comment]
Follow troubleshooting guide, do a complete reinstall of the mod in a brand new userfolder. See if that helps. If not post log files, I don't get this issue so I can't help you unless I know what's going on.

**Comment by r3eckon** [comment]
Closing this because no update, if you still get the issue reopen and post your log files.
