### ISSUE TITLE
Cannot change vehicle

### ISSUE THREAD

**Issue by flappelapper** [r3eckon/BNG-BeamLegalRacing#41]
Any time I try to change vehicle it says "Loading. Please wait" or whatever, but nothing ever happens. My entire UI freezes, and I can no longer leave the scenario. The game itself still works like normal, and I can still drive around. The only UI feature that works is towing my car. 
[beamng.1.log](https://github.com/user-attachments/files/16991595/beamng.1.log)
[beamng.log](https://github.com/user-attachments/files/16991596/beamng.log)

I was going to open the game again to get another log for this issue, and then it broke even more.

I now don't even get a car when I open the scenario, and can't do anything at all.

[nocar.log](https://github.com/user-attachments/files/16991664/nocar.log)

https://github.com/user-attachments/assets/98507c0f-0a42-4679-9f3f-6d94c139d215

**Comment by SalazarElite** [comment]
update your game to 0.33.1 and your mod to 1.16.5

**Comment by flappelapper** [comment]
Are you saying this is why it's broken or is that a troubleshooting step lol

**Comment by SalazarElite** [comment]
I'm saying that I already encountered this same problem and updating the mod solved the problem.

**Comment by r3eckon** [comment]
If you still get the issue after updating your mod start from a fresh save, delete your log files, delete your userfolder and do a clean install of the mod. As soon as you get a problem post your log files here.

**Comment by flappelapper** [comment]
updated and started from scratch
