### ISSUE TITLE
Can't abandon scenario

### ISSUE THREAD

**Issue by maybeaast** [r3eckon/BNG-BeamLegalRacing#42]
Every time I spend more than a few minutes in the beamlr scenario I can't abandon it in order to save my progress properly, as the "abandon" button simply doesn't work, so I'm forced to quit the game from the main menu.

**Comment by r3eckon** [comment]
Post log files.

**Comment by maybeaast** [comment]
> Post log files.

Sorry for not answering earlier, I haven't been able to reproduce the problem ever since I made this post so I guess it's fixed.
