### ISSUE TITLE
West Coast Darkness with BeamLR

### ISSUE THREAD

**Issue by DiegoRibeiro2003** [r3eckon/BNG-BeamLegalRacing#43]
When I start the west coast map, with the "Beam LR" mod installed, the entire map looks like this. Any solution?
Beam NG 0.32.1 version
I've already tried versions 16, 16.1 and 16.2 of BeamLR

![screenshot_2024-09-14_15-00-55](https://github.com/user-attachments/assets/2007d3af-be46-40ea-835c-bae92f986d5d)
Without the mod, the map works normally

**Comment by r3eckon** [comment]
Map is made in BeamNG version 0.32.5 and is probably not compatible with old level files. Update your game then follow [troubleshooting steps](https://github.com/r3eckon/BNG-BeamLegalRacing/blob/main/troubleshooting.md).
