### ISSUE TITLE
BNG UPDATED TO 0.33

### ISSUE THREAD

**Issue by FelpszadaSc** [r3eckon/BNG-BeamLegalRacing#49]
The mod is incompatible with the new version, has it removed the spanw from the menu and in the home, is the mod expected to be updated?

![error beam](https://github.com/user-attachments/assets/3d862efe-5705-47f7-8ccb-91704f81f744)

the mod even opens but when it loads it gives an error and crashes in bng

**Comment by FelpszadaSc** [comment]
![error beam](https://github.com/user-attachments/assets/e0aaacd5-5442-41ba-8441-ede3ef6441a3)
 one more error

**Comment by FelpszadaSc** [comment]
I left a video via link


https://files.fm/f/ypvurc7s9g

**Comment by r3eckon** [comment]
Bro it's been less than a day since the game was updated, you don't need to make a github issue for this.
