### ISSUE TITLE
Taillight missing on wendover

### ISSUE THREAD

**Issue by abodyeasy** [r3eckon/BNG-BeamLegalRacing#5]
Hi, sorry for making another new issue, I recently tried to modify my wendover and make it look normal, but for some reason, I could not find the Taillight for the car, tried to find it everywhere in the parts shop, what is it named? or is it not there?
![image](https://user-images.githubusercontent.com/65369877/231922279-daa1e298-a655-453e-aa1a-76d37a3a7dd2.png)

**Comment by r3eckon** [comment]
The part is called **Rear Fascia**. Before reporting missing parts as issues please check the part config menu in freeroam for the slot name. It's more user friendly and doesn't cost career money to try out parts before buying. 

![image](https://user-images.githubusercontent.com/5762743/231949416-7de770cf-52e6-4d43-bd42-c6295a82fe2c.png)

**Comment by abodyeasy** [comment]
Thanks, sorry for making a new issue, i wasn't sure what it was named, my friend kept telling me it's called "Taillights" in freeroam, my bad!

**Comment by r3eckon** [comment]
No worries, if you find a part that shows up in freeroam but not in BeamLR just let me know!
