### ISSUE TITLE
Problema apos atualização

### ISSUE THREAD

**Issue by DenerZZZ** [r3eckon/BNG-BeamLegalRacing#50]
![Uploading image.png…]()
IMPORTANT: DO NOT CREATE ISSUES ABOUT THE MOD BEING BROKEN BY A BEAMNG UPDATE. Be patient while I update the mod.

Before reporting an issue go through the troubleshooting guide and check open issues to see if someone else already reported your problem.

Attach log files, reproduction steps and any other information that can help fix the issue you are reporting.

This message is a placeholder, remove it from your issue.

**Comment by ggk1RELAX** [comment]
Thank you for creating this mod and for all the support, beamng was getting boring there wasn't much to do, but with this mod I'm playing every day I hope the company recognizes your effort, it's a great hobby
