### ISSUE TITLE
NPCs aren't moving

### ISSUE THREAD

**Issue by SalazarElite** [r3eckon/BNG-BeamLegalRacing#51]
Beamng Version: 0.33.1.0.17120
BeamLR Version: 1.16.4
Map: West Coast of the USA

This bug happens to all NPCs in the bronze league of Service Station Racing Club

No LOG files were generated by the game or the mod.
I don't know how far this bug extends 

(Edit: seems to affect all NPCs with custom behavior, traffic works normally, but regardless of the map, league and type of event (drag, racing league, etc.) the NPCs do not move)

<s>(Edit 2: this bug only happens on Vulkan)</s>
(Edit 3: It took a while, but it happened on Directx too)

The only error message is in the game console where it says:

[string "scripts/blrutils.lua"]:281: bad argument#1 to 'gmatch' (string expected, got nil)
Error while executing custom lua: work [string "scripts/blrutils.lua"]:281: bad argument#1 to 'gmatch' (string expected, got nil)

**Comment by r3eckon** [comment]
The log files are in the userfolder, the game always creates them. But thanks for letting me know, this happens almost every time the devs update a map, some waypoints and AI roads get broken.

**Comment by SalazarElite** [comment]
if you want to read many lines of nothing i can send you, i'm a dev too, i know that in those logs there are nothing

**Comment by r3eckon** [comment]
Unless you've been modding BeamNG you wouldn't know what to look for. If the game throws a lua error message in console it also shows up in the log, but this stuff is obvious. There are messages that aren't red colored errors that can help, for instance when race opponents aren't driving there's usually a message about how the AI can't find a path between two waypoints but it doesn't show up as an error so it's easy to miss.

**Comment by SalazarElite** [comment]
[beamng.2.log](https://github.com/user-attachments/files/17088277/beamng.2.log)
Here, 130 thousand lines of nothing that I reviewed myself and you can review too, in fact I have made mods not only for beamng but since GTA SA was released for PC in 2004, but you can do it yourself

**Comment by r3eckon** [comment]
Line 107706: 11050.37121|D|libbeamng.AI| Path between waypoints 'blrwp_raceA6' - 'blrwp_raceA7' Not Found

This is what I mean by easy to miss unless you know what to look for. This line tells me exactly which waypoints are bugged and I found it in seconds by CTRL+F the term "waypoints" as I know this error is likely to appear when AI doesn't want to drive a path. It doesn't cost anything to attach logs to your bug report so you shouldn't assume they're useless, that's for me to decide.

Also you can delete the log files before causing the error when it's an error you know how to recreate. That way you don't have thousands of useless lines in there. Pretty easy to miss the important stuff otherwise.

**Comment by SalazarElite** [comment]
great, if you need any more help just ask

**Comment by r3eckon** [comment]
Yeah I just saw a video from Italy where the problem happens, seems like devs have changed something about waypoints that broke the race path waypoints. I'll have to go through every map to fix them, usually it's just the maps that get major updates but clearly something else was changed this time.

**Comment by SalazarElite** [comment]
![image](https://github.com/user-attachments/assets/50e3ff10-8e7f-4185-b7f5-74e5703add2c)
@r3eckon can you take a look at this? every car hits this every time, i don't know if it is a bug in your mod or the game, but this happen every time, maybe changing the checkpoint location help?
