### ISSUE TITLE
I cant change parts on some cars

### ISSUE THREAD

**Issue by guzzzzzzzs** [r3eckon/BNG-BeamLegalRacing#57]
I tried to change parts like the burnside gearbox and the Miramar suspension but i cant change them and when i go back to edit car the part duplicates the one i already had

**Comment by r3eckon** [comment]
Post log files.

**Comment by guzzzzzzzs** [comment]
> Post log files.

I'm not at home right now but how do I do that?

**Comment by r3eckon** [comment]
They're found in the userfolder. Attach them to a post here. This is explained in the troubleshooting guide which you should go through before reporting issues.

**Comment by guzzzzzzzs** [comment]
> They're found in the userfolder. Attach them to a post here. This is explained in the troubleshooting guide which you should go through before reporting issues.

I put the mod in a separate folder within the mods, I have some things to do now but I'll test it later, if it goes wrong I'll tell you here, sorry for the inconvenience man

**Comment by guzzzzzzzs** [comment]
> Post log files.

[beamng-dxDiag.txt](https://github.com/user-attachments/files/17157172/beamng-dxDiag.txt)
[beamng-launcher.log](https://github.com/user-attachments/files/17157176/beamng-launcher.log)
[beamng-launcher.1.log](https://github.com/user-attachments/files/17157178/beamng-launcher.1.log)
[beamng.log](https://github.com/user-attachments/files/17157183/beamng.log)
Are these the logs?

**Comment by guzzzzzzzs** [comment]
Sorry, I managed to fix the mod, I just needed to extract it, sorry for the inconvenience
