### ISSUE TITLE
bug in the steering wheel of the vehicles

### ISSUE THREAD

**Issue by AndersonPGS** [r3eckon/BNG-BeamLegalRacing#58]
https://github.com/user-attachments/assets/5cff117c-2a1b-4be8-978e-ae423140be76

When I activate the mod, the vehicles have the "fallen" steering wheel bug

**Comment by BARCODE-ICE** [comment]
Cara essa parada é porque a versão do seu jogo ta desatualizada, aconteceu comigo só resolvi depois que atualizei a versão do jogo.

**Comment by AndersonPGS** [comment]
> Cara essa parada é porque a versão do seu jogo ta desatualizada, aconteceu comigo só resolvi depois que atualizei a versão do jogo.

Qual a versao atual do seu jogo?

**Comment by BARCODE-ICE** [comment]
Atualmente estou usando a 0.33.1.0

**Comment by r3eckon** [comment]
Yeah 0.32.0 is way out of date. That's probably what causes this bug because nothing about this mod changes steering wheel props.
