### ISSUE TITLE
bug in tires

### ISSUE THREAD

**Issue by WTS048** [r3eckon/BNG-BeamLegalRacing#59]
After this new game update to fix bugs, I had problems putting the tires on the rear wheel, it doesn't appear on the dashboard
![Uploading Captura de tela 2024-09-28 092900.png…]()

**Comment by WTS048** [comment]
![Uploading Captura de tela 2024-09-28 092900.png…]()

**Comment by r3eckon** [comment]
I can't see your image, also not sure what you mean. You mean you can't find tires in the part edit menu? If you don't have compatible tires in your inventory the slot won't show up.

**Comment by WTS048** [comment]
Yes, I have tires compatible with the wheel but it doesn't appear in the edit menu, sorry for my English, I'm from Brazil

**Comment by r3eckon** [comment]
Send me the name of the wheels so I can take a look.

**Comment by r3eckon** [comment]
Also the car they're attached to, basically as much info as possible on the config as you can think of will help.

**Comment by WTS048** [comment]
![Captura de tela 2024-09-28 210556](https://github.com/user-attachments/assets/57f8f95a-b243-472a-ab46-9b04453ef87c)

**Comment by WTS048** [comment]
I have already tried to install most of the wheels, every time I tried, the tire to install did not appear, but it appears in the purchase option

**Comment by WTS048** [comment]
I'll try to install the game and the mod again, if it works I'll close the ticket

**Comment by r3eckon** [comment]
I just need to know the name of the wheels so I can check myself. I'm talking about the wheel, not the tire. The name like "Alder Dragger 15x7" and such.

**Comment by WTS048** [comment]
I managed it, I think it was some mod causing conflict, thank you
