### ISSUE TITLE
Migrate `Releases/` folder to GitHub releases

### ISSUE THREAD

**Issue by Frontesque** [r3eckon/BNG-BeamLegalRacing#6]
In the interest of simplicity for downloading aswell as giving you a change log for each version, I suggest you use the GitHub releases tab of the repo to host your release.

This comes with a few benefits as I mention below:

- GitHub tracks your version information and keeps it sorted nicely
- You don't need to push a repo update for every release
- You are able to mark releases as "experimental" or "pre-release" if you plan on making beta/staging builds eventually
- GitHub tracks downloads for you from each release to let you know how many people are actually using your project
- GitHub provides a please for you to include a change log along with each release

There are probably more that I can't think of but hopefully this helps

**Comment by r3eckon** [comment]
I'll probably do this at some point, thanks for the tip!
