### ISSUE TITLE
DRAGSTRIP RACE CLUB Opponents not moving

### ISSUE THREAD

**Issue by DiegoRibeiro2003** [r3eckon/BNG-BeamLegalRacing#62]
The oponnent is not moving at DRAGSTRIP RACE CLUB on the WestCoast Map
[beamng.log](https://github.com/user-attachments/files/17215082/beamng.log)

**Comment by r3eckon** [comment]
Fixed. I don't know what the fuck devs did to AI pathing but without autoJunction enabled the AI won't drive a given path even if all the waypoints are on a single decalroad.
